config/routes.rb
Rails.application.routes.draw do  
  
 
get 'notification/index'
post '/bot/auth', to: 'bot/start#auth'
get '/bot/init', to: 'bot/start#init'
post '/bot/conversation', to: 'bot/start#conversation'
root 'admin/dashboard#index'

get '/cardapio/:id', to: 'menu/cardapio#index'
get '/notifica_pedido/:id', to: 'notification#index'
  namespace :menu do
    root 'cardapio#index'
    
    get '/product/:id', to: 'cardapio#produto_unico'
    get '/group/:id', to: 'cardapio#grupo'
    post '/armazena_pedido', to: 'cardapio#armazena_pedido'
    get '/detalhes_pedido', to: 'cardapio#detalhes_pedido' 
    get '/limpar_carrinho', to: 'cardapio#limpar_carrinho' 
    post '/altera_forma_pagamento', to: 'cardapio#altera_forma_pagamento'
    post '/altera_endereco_entrega', to: 'cardapio#altera_endereco_entrega'
    get '/finaliza_pedido', to: 'cardapio#finaliza_pedido'
    post '/finaliza_pedido/salvar', to: 'cardapio#salvar_perfil'
    get '/pedido_finalizado', to: 'cardapio#concluido'
    get '/perfil', to: 'cardapio#perfil'
  end

  namespace :admin do
    root 'dashboard#index'
    get '/impressao/:id', to: 'printer#index'
    resources :delivery
    resources :client
    resources :product
    resources :category
    resources :company
    resources :product_simple
    resources :payment
    resources :admin_profile, only: [:edit, :update]
    get '/taxa_entrega', to: 'company#taxa_entrega'
    get '/consulta_pedido', to: 'company#consulta_pedido'
    get '/atualizaStatus', to: 'company#atualiza_pedido'
    resources :pedidos, only:[:edit, :update, :index]
    get '/imprimir/teste', to: 'company#impressao'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    confirmations: 'admins/confirmations',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    unlocks: 'admins/unlocks'
  }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :admin_profile
         has_many :companies
end

app/models/admin_profile.rb
class AdminProfile < ApplicationRecord
    belongs_to :admin
    has_one_attached :avatar_admin
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :company
  has_one_attached :avatar_category
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord  
  belongs_to :admin
  has_many :products
  has_one_attached :avatar_company

  enum status: [:pendente, :ativa, :inativa]
end

app/models/delivery_price.rb
class DeliveryPrice < ApplicationRecord
  belongs_to :company
end

app/models/itens_pedido.rb
class ItensPedido < ApplicationRecord
  belongs_to :pedido
end

app/models/licenca.rb
class Licenca < ApplicationRecord
    
end

app/models/payment.rb
class Payment < ApplicationRecord
    enum tipo: [:credito, :debito, :avista]
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :client
  enum status: [:pendente, :aceito, :recusado, :preparacao, :entrega, :concluido]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
  belongs_to :category, optional: true
  has_one_attached :avatar_product

 # monetize :valor_cents
 # monetize :valor_promocional_cents

  def self.new_product
   #puts "#{self}"
  end
end

app/models/product_simple.rb
class ProductSimple < ApplicationRecord
    has_many :side_products_setps
    #monetize :valor_cents
end

app/models/product_step.rb
class ProductStep < ApplicationRecord
  belongs_to :product
  belongs_to :company
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :company
end

app/models/sale_product.rb
class SaleProduct < ApplicationRecord
  belongs_to :sale
  belongs_to :product
end

app/models/side.rb
class Side < ApplicationRecord
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/delivery_controller.rb
class Admin::DeliveryController < AdminController
  before_action :edit, only: [:update]
  def index
    @entregas = DeliveryPrice.where(company_id: $empresa)
  end

  def new
    @delivery = DeliveryPrice.new
  end

  def create    
    @delivery = DeliveryPrice.new(set_params)
    if @delivery.valor.present? 
      valor = params[:delivery_price][:valor].gsub(',','.').to_f    
    end

    @delivery.valor = valor
    @delivery.company_id = $empresa
    respond_to do |format|
      if @delivery.save
        format.html{redirect_to admin_delivery_index_path, notice: 'Taxa adicionada com Sucesso'}
      else
        format.html{render :new, notice: 'Erro ao adicionar Taxa'}
      end
    end
  end

  def edit
    @delivery = DeliveryPrice.find(params[:id])
  end

  def update
    if params[:delivery_price][:valor].present? 
      valor = params[:delivery_price][:valor].gsub(',','.').to_f    
    end
    @delivery.valor = valor    
    respond_to do |format|
      if @delivery.save
        format.html{redirect_to admin_delivery_index_path, notice: 'Taxa editada com Sucesso'}
      else
        format.html{render :new, notice: 'Erro ao editar Taxa'}
      end
    end
  end

  def set_params
    params.require(:delivery_price).permit(:bairro_nome, :valor)
  end
end

app/helpers/admin/delivery_helper.rb
module Admin::DeliveryHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/delivery/edit.html.erb
<%=form_with(url: admin_delivery_path, model: @delivery, method: :patch, local: true) do |form|%>
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-4">Editando Taxas de Entrega</h4>   
    
                    <div class="row">
                        
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="formrow-email-input">Bairro</label>                            
                                <%=form.text_field :bairro_nome, class: 'form-control'%>
                            </div>
                        </div>                        
                        <div class="col-md-3">
                            <label for="input-currency-valor">Valor</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="option-date">R$</span>
                                </div>
                                <input type="text" name="delivery_price[valor]" id="input-currency-valor" class="form-control money" placeholder="00,00" value="<%= number_to_currency(@delivery.valor, :unit => 'R$ ')%>">
                            </div>
                        </div>                      
                    </div>            
            </div>
        </div>            
        <div class="card">
            <div class="card-body">
                <div>
                    <button type="submit" class="btn btn-primary btn-block w-md">Salvar</button>
                </div>
            </div>
        </div>
    </div>
    <%end%>

app/views/admin/delivery/index.html.erb
<div class="col-sm-12">
    <div class="card">
        <div class="card-body">
            <div class="row"> 
                <div class="col-sm-2">                    
                </div>
                <div class="col-sm-10 canto">                    
                    <%=link_to new_admin_delivery_path, class: 'btn btn-success waves-effect waves-light w-sm' do%>
                        <i class="mdi mdi-pencil d-block font-size-16"></i> Novo
                    <%end%>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
  th{
      text-align: center;
  }
</style>
  
<div class="col-sm-12">
    <div class="card">
        <div class="card-body">
            <br>
            <div class="table-responsive">
                <table class="table table-centered table-nowrap mb-0">
                    <thead class="thead-light">
                        <tr>
                            <th>Bairro</th>                            
                            <th>Taxa(R$)</th>                                                        
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                     <% @entregas.each do |delivery|%>
                        <tr>                            
                            <td><%=delivery.bairro_nome%></td>
                            <td style="text-align: center;"><%=delivery.valor%></td>                                                      
                            <td style="text-align: center;"> 
                                <%=link_to "Editar", edit_admin_delivery_path(delivery), class: 'btn btn-primary btn-sm btn-rounded waves-effect waves-light'%>
                            </td>
                        </tr>
                      <%end%>
                    </tbody>
                </table>
            </div>           
        </div>
    </div>
</div>

app/views/admin/delivery/new.html.erb
<%=form_with(url: admin_delivery_index_path, model: @delivery, method: :post, local: true) do |form|%>
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-4">Cadastro de Taxas de Entrega</h4>   
    
                    <div class="row">
                        
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="formrow-email-input">Bairro</label>                            
                                <%=form.text_field :bairro_nome, class: 'form-control'%>
                            </div>
                        </div>                        
                        <div class="col-md-3">
                            <label for="input-currency-valor">Valor</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="option-date">R$</span>
                                </div>
                                <input type="text" name="delivery_price[valor]" id="input-currency-valor" class="form-control money" placeholder="00,00">
                            </div>
                        </div>                      
                    </div>            
            </div>
        </div>            
        <div class="card">
            <div class="card-body">
                <div>
                    <button type="submit" class="btn btn-primary btn-block w-md">Salvar</button>
                </div>
            </div>
        </div>
    </div>
    <%end%>